### ISSUE TITLE
create prototype of main page

### ISSUE THREAD

**Issue by nurik23** [jamilya824/com-site#1]
1) Come up with the design (in Photoshop)
2) Present new design

**Comment by nurik23** [comment]
![screenshot from 2018-09-14 11-37-34](https://user-images.githubusercontent.com/29931886/45531686-b0353800-b812-11e8-8ee5-8956ba34bb2c.png)
![screenshot from 2018-09-14 11-37-38](https://user-images.githubusercontent.com/29931886/45531689-b2979200-b812-11e8-91d4-5b5614654d0a.png)

**Comment by nurik23** [comment]
it is ready design of home page. Start working on it.

**Comment by venerakanybekova** [comment]
👍

пт, 14 сент. 2018 г., 11:40 nurdoolot.tagaev <notifications@github.com>:
