### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nurik23** [jamilya824/com-site#12]
page "Calendar">>"Academic calendar"  does not work correctly.
![image](https://user-images.githubusercontent.com/29931886/45637956-91ae9580-bacd-11e8-9af8-26c40e82d3fa.png)

**Comment by venerakanybekova** [comment]
Academic calendar давайте на гланую iaau страницу отправлять?

**Comment by baevselba** [comment]
We decided to delete this page from website
